use_frameworks!

platform :ios, '9.0'

target 'JZEazyVideoPlayer_Example' do
  pod 'JZEazyVideoPlayer', :path => '../'

  target 'JZEazyVideoPlayer_Tests' do
    inherit! :search_paths

    
  end
end
